### ISSUE TITLE
Part duplication is creating Fields on the part being duplicated

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms-multi-part#101]
Part duplication is creating Fields on the part being duplicated that have the same field key as the fields on the newly created part.

Replication steps:
duplicate a part of a multi-part form
you will see a copy of the part added, but a duplicate of the fields are also added on the original part.

### Environment ###
Home URL:                http://localhost/wordpress3
Site URL:                http://localhost/wordpress3
Ninja Forms Version:     3.1.4
WP Version:              4.8
WP Multisite Enabled:    No
Web Server Info:         Apache
TLS Version:             unknown
PHP Version:             5.2.17
MySQL Version:           5.6.35
PHP Locale:              negative_sign:
WP Memory Limit:         40M
WP Debug Mode:           Yes
WP Language:             Default
WP Max Upload Size:      32 MB
PHP Post Max Size:       32M
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      
SUHOSIN Installed:       No
Server IP Address:       ::1
Host Name:               localhost
SMTP:                    localhost
smtp_port:               25
Default Timezone:        America/New_York

### Plugins ###
Installed Plugins:       Ninja Forms - Conditional Logic by The WP Ninjas version 3.0.14
                         Ninja Forms - Multi-Part Forms by The WP Ninjas version 3.0.17
                         Ninja Forms by The WP Ninjas version 3.1.4

**Comment by kstover** [comment]
This should be taken care of in the most recent version. I can't replicate the issue.

**Comment by kjohnson** [comment]
I was able to re-create this issue on `develop` (up-to-date).

Steps to Reproduce:
- Add new part.
- Add 3 textboxes and 1 textarea to the new part.
- Duplicate the new part.

Related #84.

---
Support Ticket: https://wpninjas.kustomerapp.com/app/customers/59748de9291ce90011bd9867/event/59871e402b0b800010e17503

**Comment by wpnzach** [comment]
@kjohnson This is still happening in the current release of MPF.  It only happens when Layout and Styles is also active.  Likely related to #110
