### ISSUE TITLE
Required fields not stopping user from moving to the next part

### ISSUE THREAD

**Issue by ericwindham** [wpninjas/ninja-forms-multi-part#122]
Create a multi-part form with required field on at least one part that is not the final part. 

Turn on 'Validate Each Part' under Advance>Mult-Part

Preview the form. Go to the next page without entering a value in the required field. The plug-in should prevent the user from moving to the next page without filling out the required field. It currently does not.

Caveat: This works correctly with Layouts and Styles activated. So make sure that add-on is deactivated for testing purposes.

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/59c672384de97b0010df9971/event/5a40e273e4635c00012ac149

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5a4eb2b718ea9700016fe060/event/5a4eb2b74f13930001ffb07f

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5a5cb7e1dcbb120001e1b46d/event/5a5d0d862596b7000111027e
