### ISSUE TITLE
Skipe to the next Page

### ISSUE THREAD

**Issue by ryscript** [wpninjas/ninja-forms-multi-part#126]
Halloo guys just wanted to know if it's possible or anyone can guide me in the correct direction, I wanted to skip the next form to the next form depending on the user selected field option value.

e.g. assume we're on Page 1.
Form 1
- If user click Yes (let say on the field), then
- Then I wanted the form to go to Page 3, instead of the next Page 2, otherwise, if the user clicks No
- It goes to the next preceding form which is Page 2.

Is there a way to do this?

Thanks

**Comment by sridhargoshika** [comment]
@ryscript how to did you solve this problem?

**Comment by ryscript** [comment]
@sridhargoshika  you may use a Conditional functionality right in the NF Dashboard/settings.
