### ISSUE TITLE
Duplicate isn't giving new field keys

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms-multi-part#84]

**Comment by kjohnson** [comment]
Seeing a new report of this issue.
Also reproduced locally.

Steps to Reproduce:
- Add new part.
- Add 3 textboxes and 1 textarea to the new part.
- Duplicate the new part.

Related #101

---

Support Ticket: https://wpninjas.kustomerapp.com/app/customers/59748de9291ce90011bd9867/event/59871e402b0b800010e17503

**Comment by kjohnson** [comment]
Looks like the issue is actually double duplication. Re-closing.
